# Generated by Django 4.2.2 on 2023-06-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='Quote',
            new_name='quote',
        ),
    ]
